# Generated by Django 3.2.8 on 2021-11-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_auto_20211010_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='carbohydrate',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('sanacks', 'sanacks')], max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userfooditem',
            name='fooditem',
            field=models.ManyToManyField(to='count.Fooditem'),
        ),
    ]
